networks:
  proxy:
    external: true

services:
  openspeedtest:
    image: openspeedtest/latest
    container_name: ${CONTAINER_NAME:-openspeedtest}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
    #ports:
    #  - 3000:3000
    networks:
      proxy:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.rtr-openspeedtest.entrypoints=https
      - traefik.http.routers.rtr-openspeedtest.rule=Host(`${TRAEFIK_SUBJECT_CN:?}`)
      - traefik.http.middlewares.mdw-buffer-openspeedtest.buffering.maxRequestBodyBytes=10000000000
      - traefik.http.routers.rtr-openspeedtest.middlewares=mdw-buffer-openspeedtest
      - traefik.http.services.svc-openspeedtest.loadbalancer.server.scheme=http
      - traefik.http.services.svc-openspeedtest.loadbalancer.server.port=3000
      - traefik.http.routers.rtr-openspeedtest.service=svc-openspeedtest