networks:
  stack:
  proxy:
    external: true

services:
  joplin:
    image: joplin/server:latest
    container_name: joplin
    hostname: ${HOSTNAME}
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    networks:
      stack:
      proxy:
    #ports:
    #  - ${APP_PORT:-22300}:22300
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.rtr-joplin.entryPoints=https
      - traefik.http.routers.rtr-joplin.rule=Host(`${TRAEFIK_SUBJECT_CN:?}`)
      - traefik.http.services.svc-joplin.loadBalancer.server.scheme=http
      - traefik.http.services.svc-joplin.loadBalancer.server.port=${APP_PORT:-22300}
      - traefik.http.routers.rtr-joplin.service=svc-joplin
  db:
    image: postgres:16
    container_name: joplin_db
    hostname: Cable
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
      - POSTGRES_USER=${POSTGRES_USER:-joplin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - POSTGRES_DB=${POSTGRES_DATABASE:-joplin}
    volumes:
      - /opt/joplin/db:/var/lib/postgresql/data
    networks:
      stack: