networks:
  stack:

services:
  audiobookshelf:
    # https://www.audiobookshelf.org/
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    hostname: ${HOSTNAME}
    restart: unless-stopped
    depends_on:
      - abs-tract
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONTAINER_BASEPATH:-.}/config:/config
      - ${CONTAINER_BASEPATH:-.}/metadata:/metadata
      - ${MEDIA_BASEPATH:-.}/books/Audiobooks:/audiobooks
      - ${MEDIA_BASEPATH:-.}/books/eBooks:/ebooks
      - ${MEDIA_BASEPATH:-.}/music/Podcasts:/podcasts
    ports:
      - ${CONTAINER_PORT_HTTP:-80}:80
    networks:
      - stack

  abs-tract:
    # https://github.com/ahobsonsayers/abs-tract
    image: arranhs/abs-tract
    container_name: abs-tract
    hostname: ${HOSTNAME}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
    ports:
      - 5555:5555
    networks:
      - stack