networks:
  proxy:
    external: true

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: ${CONTAINER_NAME:-heimdall}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ${CONTAINER_BASEPATH:-./}:/config
    #ports:
    #  - 80:80
    #  - 443:443
    networks:
      proxy:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.rtr-heimdall.entrypoints=https
      - traefik.http.routers.rtr-heimdall.rule=Host(`${TRAEFIK_SUBJECT_CN:?}`)
      - traefik.http.services.svc-heimdall.loadbalancer.server.scheme=http
      - traefik.http.services.svc-heimdall.loadbalancer.server.port=80
      - traefik.http.routers.rtr-heimdall.service=svc-heimdall