networks:
  stack:
  proxy:
    external: true

services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: ${CONTAINER_NAME:-bookstack}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - TZ=${TZ:-UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - APP_URL=${APP_URL:-http://bookstack:80}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-bookstack}
      - DB_USER=${DB_USER:-bookstack}
      - DB_PASS=${DB_PASS:-Key4-My-Squeeky-StackOf-Language-Books}
    volumes:
      - ${CONTAINER_BASEPATH:-/opt/bookstack}:/config
    #ports:
    #  - 80:80
    networks:
      stack:
      proxy:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.rtr-bookstack.entrypoints=https
      - traefik.http.routers.rtr-bookstack.rule=Host(`${TRAEFIK_SUBJECT_CN:?}`)
      - traefik.http.services.svc-bookstack.loadbalancer.server.scheme=http
      - traefik.http.services.svc-bookstack.loadbalancer.server.port=80
      - traefik.http.routers.rtr-bookstack.service=svc-bookstack

  db:
    image: lscr.io/linuxserver/mariadb
    container_name: ${CONTAINER_DB_NAME:-bookstack_db}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-Key4-My-Squeeky-StackOf-Language-Books}
      - MYSQL_DATABASE=${DB_DATABASE:-bookstack}
      - MYSQL_USER=${DB_USER:-bookstack}
      - MYSQL_PASSWORD=${DB_PASS:-Key4-My-Squeeky-StackOf-Language-Books}
    volumes:
      - ${CONTAINER_DB_BASEPATH:-${CONTAINER_BASEPATH:-/opt/bookstack}/db}:/config
    networks:
      stack:

#  mariadb:
#    image: mariadb
#    restart: unless-stopped
#    environment:
#      - MARIADB_ROOT_PASSWORD=${DB_PASS:-Key4-My-Squeeky-StackOf-Language-Books}
#      - MARIADB_DATABASE=${DB_DATABASE:-bookstack}
#      - MARIADB_USER=${DB_USER:-bookstack}
#      - MARIADB_PASSWORD=${DB_PASS:-Key4-My-Squeeky-StackOf-Language-Books}
#    volumes:
#      - ${CONTAINER_DB_BASEPATH:-${CONTAINER_BASEPATH:-/opt/bookstack}/db}:/var/lib/mysql
#    networks:
#      stack: