networks:
  proxy:
    external: true

services:
  http-echo:
    image: hashicorp/http-echo:latest
    container_name: ${CONTAINER_NAME:-http-echo}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    command:
    #  - -text=${ECHO_TEXT}
      - -listen=${CONTAINER_PORT_HTTP:-5678}
      - -status-code=${STATUS_CODE:-200}
      - -version=false
    environment:
      - ECHO_TEXT=${ECHO_TEXT:-OK}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    #ports:
    #  - ${CONTAINER_PORT_HTTP:-5678}:${CONTAINER_PORT_HTTP:-5678}
    networks:
      proxy:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.rtr-http-echo.entrypoints=https
      - traefik.http.routers.rtr-http-echo.rule=Host(`${TRAEFIK_SUBJECT_CN:?}`)
      - traefik.http.services.svc-http-echo.loadbalancer.server.scheme=http
      - traefik.http.services.svc-http-echo.loadbalancer.server.port=${CONTAINER_PORT_HTTP:-5678}
      - traefik.http.routers.rtr-http-echo.service=svc-http-echo