networks:
  proxy:
    external: true

services:
  # https://docs.linuxserver.io/images/docker-librewolf/
  librewolf:
    image: lscr.io/linuxserver/librewolf:latest
    container_name: ${CONTAINER_NAME:-librewolf}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    shm_size: "1gb"
    environment:
      - TZ=${TZ:-UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ${CONTAINER_BASEPATH:-/opt/librewolf}:/config
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      proxy:
