networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: ${CONTAINER_NAME:-traefik}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    command:
      - --configFile=${TRAEFIK_CONFIG_FILE:-/etc/traefik/traefik.yaml}
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONTAINER_BASEPATH:-/etc/traefik}/traefik.yaml:${TRAEFIK_CONFIG_FILE:-/etc/traefik/traefik.yaml}:ro
      - ${CONTAINER_BASEPATH:-/etc/traefik}/conf.d:/etc/traefik/conf.d:ro
      - ${CONTAINER_BASEPATH:-/etc/traefik}/certs/acme.json:${TRAEFIK_ACME_FILE:-${TRAEFIK_ACME_PATH:-/etc/traefik/certs}/acme.json}
      - ${CONTAINER_LOGPATH:-/var/log/traefik}/traefik.log:${TRAEFIK_LOG_FILE:-${TRAEFIK_LOG_PATH:-/var/log/traefik}/traefik.log}
      - ${CONTAINER_LOGPATH:-/var/log/traefik}/access.log:${TRAEFIK_ACCESSLOG_FILE:-${TRAEFIK_LOG_PATH:-/var/log/traefik}/access.log}
    ports:
      - 80:80
      - 443:443
      - 4443:4443
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.rtr-traefik.entryPoints=dashboard
      - traefik.http.routers.rtr-traefik.rule=Host(`${TRAEFIK_SUBJECT_CN:?}`)
      - traefik.http.routers.rtr-traefik.service=api@internal