networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: ${CONTAINER_NAME:-traefik}
    hostname: ${CONTAINER_HOSTNAME:-${HOSTNAME}}
    restart: unless-stopped
    command:
      - --configFile=${TRAEFIK_CONFIG_FILE:-/etc/traefik/traefik.yaml}
    security_opt:
      - no-new-privileges:true
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN:?CF_DNS_API_TOKEN is missing}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONTAINER_BASEPATH}/traefik.yaml:${TRAEFIK_CONFIG_FILE:-/etc/traefik/traefik.yaml}:ro
      - ${CONTAINER_BASEPATH}/conf.d:/etc/traefik/conf.d:ro
      - ${CONTAINER_BASEPATH}/certs/acme.json:${TRAEFIK_ACME_FILE:-${TRAEFIK_ACME_PATH:-/etc/traefik/certs}/acme.json}
      - ${CONTAINER_LOGPATH:-/var/log/traefik}/traefik.log:${TRAEFIK_LOG_FILE:-${TRAEFIK_LOG_PATH:-/var/log/traefik}/traefik.log}
      - ${CONTAINER_LOGPATH:-/var/log/traefik}/access.log:${TRAEFIK_ACCESSLOG_FILE:-${TRAEFIK_LOG_PATH:-/var/log/traefik}/access.log}
    ports:
      - ${CONTAINER_PORT_HTTP:-80}:80
      - ${CONTAINER_PORT_HTTPS:-443}:443
      - ${CONTAINER_PORT_DASHBOARD:-4443}:4443
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.middlewares.mdw-bauth-${TRAEFIK_SERVICE:-traefik}.basicauth.users=${TRAEFIK_LOGIN}
      - traefik.http.routers.rtr-${TRAEFIK_SERVICE:-traefik}.middlewares=mdw-bauth-${TRAEFIK_SERVICE:-traefik}
      - traefik.http.routers.rtr-${TRAEFIK_SERVICE:-traefik}.entrypoints=dashboard
      - traefik.http.routers.rtr-${TRAEFIK_SERVICE:-traefik}.rule=${TRAEFIK_ROUTER_RULE:-Host(`${TRAEFIK_SUBJECT_CN:?TRAEFIK_ROUTER_RULE is missing}`)}
      - traefik.http.routers.rtr-${TRAEFIK_SERVICE:-traefik}.tls=true
      - traefik.http.routers.rtr-${TRAEFIK_SERVICE:-traefik}.tls.certresolver=${TRAEFIK_CERTRESOLVER:-le_cloudflare}
      - traefik.http.routers.rtr-${TRAEFIK_SERVICE:-traefik}.tls.domains[0].main=${TRAEFIK_SUBJECT_CN:?TRAEFIK_SUBJECT_CN is missing}
      - traefik.http.routers.rtr-${TRAEFIK_SERVICE:-traefik}.service=api@internal