global:
  checkNewVersion: true
  sendAnonymousUsage: false

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    watch: true
    network: proxy
  file:
    directory: /etc/traefik/conf.d
    watch: true

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
    reusePort: true
    asDefault: true
    http:
      tls: {}

serversTransport:
  insecureSkipVerify: false

certificatesResolvers:
  default:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: ${TRAEFIK_ACME_EMAIL:?}
      storage: ${TRAEFIK_ACME_FILE:-${TRAEFIK_ACME_PATH:-/etc/traefik}/acme.json}
      keyType: EC384 # 'EC256', 'EC384', 'RSA2048', 'RSA4096', 'RSA8192'. Default RSA4096
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53
  staging:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: ${TRAEFIK_ACME_EMAIL:?}
      storage: ${TRAEFIK_ACME_FILE:-${TRAEFIK_ACME_PATH:-/etc/traefik}/acme.json}
      keyType: EC384 # 'EC256', 'EC384', 'RSA2048', 'RSA4096', 'RSA8192'. Default RSA4096
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53

api:
  dashboard: true
  debug: true
  disableDashboardAd: true

log:
  #filePath: ${TRAEFIK_LOG_FILE:-${TRAEFIK_LOG_PATH:-/var/log/traefik}/traefik.log}
  #format: json
  level: DEBUG # TRACE, DEBUG, INFO, WARN, ERROR, FATAL, PANIC

accessLog:
  #filePath: ${TRAEFIK_ACCESSLOG_FILE:-${TRAEFIK_LOG_PATH:-/var/log/traefik}/access.log}
  #format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep

experimental:
  plugins:
    crowdsecBouncer:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.3.3"
    staticResponse:
      moduleName: "github.com/jdel/staticresponse"
      version: "v0.0.1"
    cloudflareWarp:
      moduleName: "github.com/BetterCorp/cloudflarewarp"
      version: "v1.3.3"
    blockPath:
      moduleName: "github.com/traefik/plugin-blockpath"
      version: "v0.2.1"
    rewriteBody:
      moduleName: "github.com/traefik/plugin-rewritebody"
      version: "v0.3.1"
    #geoBlock:
    #  moduleName: "github.com/PascalMinder/GeoBlock"
    #  version: "v0.2.8"