global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  #filePath: ${TRAEFIK_LOG_FILE:-${TRAEFIK_LOG_PATH:-/var/log/traefik}/traefik.log}
  #format: json
  level: INFO

accessLog:
  #filePath: ${TRAEFIK_ACCESSLOG_FILE:-${TRAEFIK_LOG_PATH:-/var/log/traefik}/access.log}
  #format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
  dashboard:
    address: :4443

serversTransport:
  insecureSkipVerify: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: proxy
  file:
    directory: /etc/traefik/conf.d
    watch: true

experimental:
  plugins:
    crowdsecBouncer:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.3.2"
    staticResponse:
      moduleName: "github.com/jdel/staticresponse"
      version: "v0.0.1"
    cloudflareProxy:
      moduleName: "github.com/BetterCorp/cloudflarewarp"
      version: "v1.3.3"
