networks:
  proxy:
    external: true

services:
  homarr:
    # https://homarr.dev/docs/getting-started/installation/
    image: ghcr.io/ajnart/homarr:latest
    container_name: ${CONTAINER_NAME:-homarr}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - DATABASE_URL=file:/app/data/configs/db.sqlite
      #- DOCKER_GID=999 # Must be same as host docker group id
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${CONTAINER_BASEPATH:-./configs}:/app/data/configs
      - ${CONTAINER_BASEPATH:-./icons}:/app/public/icons
      - ${CONTAINER_BASEPATH:-./data}:/data
    #ports:
    #  - 7575:7575
    networks:
      proxy:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.rtr-homarr.entrypoints=https
      - traefik.http.routers.rtr-homarr.rule=Host(`${TRAEFIK_SUBJECT_CN:?}`)
      - traefik.http.services.svc-homarr.loadbalancer.server.scheme=http
      - traefik.http.services.svc-homarr.loadbalancer.server.port=80
      - traefik.http.routers.rtr-homarr.service=svc-homarr