networks:
  proxy:
    external: true

services:
  trilium:
    image: zadam/trilium:latest
    container_name: ${CONTAINER_NAME:-trilium}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${CONTAINER_BASEPATH:-~/trilium-data}:/home/node/trilium-data
    #ports:
    #  - 8080:8080
    networks:
      proxy:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.rtr-trilium.entryPoints=https
      ## Using subdomain:
      - traefik.http.routers.rtr-trilium.rule=Host(`${TRAEFIK_SVC_HOST:?}`)
      ## Using pathPrefix:
      #- traefik.http.routers.rtr-trilium.rule=Host(`${TRAEFIK_SVC_HOST:?}`) && (PathPrefix(`/${TRAEFIK_SVC_PATHPREFIX:-notes}`) || HeaderRegexp(`Referer`, `.+/${TRAEFIK_SVC_PATHPREFIX:-notes}/?.*`))
      #- traefik.http.middlewares.mdw-redirect-trilium.redirectRegex.regex=^(https?://[^/]+)(/${TRAEFIK_SVC_PATHPREFIX:-notes})?/?([^/].*)?$
      #- traefik.http.middlewares.mdw-redirect-trilium.redirectRegex.replacement=$${1}/${TRAEFIK_SVC_PATHPREFIX:-notes}/$${3}
      #- traefik.http.middlewares.mdw-redirect-trilium.redirectRegex.permanent=true
      #- traefik.http.middlewares.mdw-rmPrefix-trilium.stripPrefix.prefixes=/${TRAEFIK_SVC_PATHPREFIX:-notes}
      #- traefik.http.middlewares.mdw-chain-trilium.chain.middlewares=mdw-redirect-trilium,mdw-rmPrefix-trilium
      #- traefik.http.routers.rtr-trilium.middlewares=mdw-chain-trilium
      - traefik.http.services.svc-trilium.loadBalancer.server.scheme=http
      - traefik.http.services.svc-trilium.loadBalancer.server.port=8080
      - traefik.http.routers.rtr-trilium.service=svc-trilium