networks:
  proxy:
    external: true

services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: ${CONTAINER_NAME:-dokuwiki}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ${CONTAINER_BASEPATH:-/opt/dokuwiki}:/config
      #- /path/to/cert.key:/config/keys/cert.key
      #- /path/to/fullchain.cer:/config/keys/cert.crt
    #ports:
    #  - 80:80
    #  - 443:443
    networks:
      proxy:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.rtr-dokuwiki.entryPoints=https
      - traefik.http.routers.rtr-dokuwiki.rule=Host(`${TRAEFIK_SUBJECT_CN:?}`)
      - traefik.http.services.svc-dokuwiki.loadBalancer.server.scheme=http
      - traefik.http.services.svc-dokuwiki.loadBalancer.server.port=80
      - traefik.http.routers.rtr-dokuwiki.service=svc-dokuwiki