services:
  watchtower:
    image: containrrr/watchtower
    container_name: ${CONTAINER_NAME:-watchtower}
    hostname: ${CONTAINER_HOSTNAME:-${HOSTNAME}}
    restart: unless-stopped
    environment:
      ### https://containrrr.dev/watchtower/arguments/
      - TZ=${TZ:-Europe/Copenhagen}
      - WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP:-true}
      #- WATCHTOWER_REMOVE_VOLUMES=${WATCHTOWER_REMOVE_VOLUMES:-false}
      #- WATCHTOWER_DEBUG=${WATCHTOWER_DEBUG:-false}
      #- WATCHTOWER_TRACE=${WATCHTOWER_TRACE:-false}
      #- WATCHTOWER_LOG_LEVEL=${WATCHTOWER_LOG_LEVEL:-info}
      #- WATCHTOWER_LOG_FORMAT=${WATCHTOWER_LOG_FORMAT:-Auto}
      #- NO_COLOR=${NO_COLOR:-false}
      #- DOCKER_HOST=${DOCKER_HOST:-unix:///var/run/docker.sock}
      #- DOCKER_API_VERSION=${DOCKER_API_VERSION:-1.24}
      #- WATCHTOWER_INCLUDE_RESTARTING=${WATCHTOWER_INCLUDE_RESTARTING:-false}
      #- WATCHTOWER_INCLUDE_STOPPED=${WATCHTOWER_INCLUDE_STOPPED:-false}
      #- WATCHTOWER_REVIVE_STOPPED=${WATCHTOWER_REVIVE_STOPPED:-false}
      #- WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_POLL_INTERVAL:-86400}
      - WATCHTOWER_LABEL_ENABLE=${WATCHTOWER_LABEL_ENABLE:-true}
      #- WATCHTOWER_DISABLE_CONTAINERS=${WATCHTOWER_DISABLE_CONTAINERS:-""}
      #- WATCHTOWER_MONITOR_ONLY=${WATCHTOWER_MONITOR_ONLY:-false}
      #- WATCHTOWER_LABEL_TAKE_PRECEDENCE=${WATCHTOWER_LABEL_TAKE_PRECEDENCE:-false}
      #- WATCHTOWER_NO_RESTART=${WATCHTOWER_NO_RESTART:-false}
      #- WATCHTOWER_NO_PULL=${WATCHTOWER_NO_PULL:-false}
      - WATCHTOWER_NO_STARTUP_MESSAGE=${WATCHTOWER_NO_STARTUP_MESSAGE:-true}
      #- WATCHTOWER_RUN_ONCE=${WATCHTOWER_RUN_ONCE:-false}
      #- WATCHTOWER_HTTP_API_UPDATE=${WATCHTOWER_HTTP_API_UPDATE:-false}
      #- WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN:-false}
      #- WATCHTOWER_HTTP_API_PERIODIC_POLLS=${WATCHTOWER_HTTP_API_PERIODIC_POLLS:-false}
      #- WATCHTOWER_HTTP_API_METRICS=${WATCHTOWER_HTTP_API_METRICS:-false}
      #- WATCHTOWER_SCOPE=${WATCHTOWER_SCOPE:-}
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE:-"0 0 4 * * *"}
      - WATCHTOWER_ROLLING_RESTART=${WATCHTOWER_ROLLING_RESTART:-true}
      - WATCHTOWER_TIMEOUT=${WATCHTOWER_TIMEOUT:-30s}
      #- DOCKER_TLS_VERIFY=${DOCKER_TLS_VERIFY:-false}
      #- WATCHTOWER_WARN_ON_HEAD_FAILURE=${WATCHTOWER_WARN_ON_HEAD_FAILURE:-auto}
      #- WATCHTOWER_NOTIFICATIONS_LEVEL=${WATCHTOWER_NOTIFICATIONS_LEVEL:-info}
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=${CONTAINER_HOSTNAME:-${HOSTNAME}}
      - WATCHTOWER_NOTIFICATIONS_DELAY=${WATCHTOWER_NOTIFICATIONS_DELAY:-2s}
      #- WATCHTOWER_NOTIFICATION_TITLE_TAG=${WATCHTOWER_NOTIFICATION_TITLE_TAG:-}
      #- WATCHTOWER_NOTIFICATION_SKIP_TITLE=${WATCHTOWER_NOTIFICATION_SKIP_TITLE:-false}
      #- WATCHTOWER_NOTIFICATION_LOG_STDOUT=${WATCHTOWER_NOTIFICATION_LOG_STDOUT:-false}
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL:?WATCHTOWER_NOTIFICATION_URL is missing}
      #- WATCHTOWER_NOTIFICATION_TEMPLATE=${WATCHTOWER_NOTIFICATION_TEMPLATE:-}
      #- WATCHTOWER_NOTIFICATION_REPORT=${WATCHTOWER_NOTIFICATION_REPORT:-}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - com.centurylinklabs.watchtower.enable=true