networks:
  proxy:
    external: true

services:
  ## https://github.com/wantguns/bin
  basedbin:
    image: wantguns/bin
    container_name: ${CONTAINER_NAME:-basedbin}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    environment:
      - BIN_PORT=${BIN_PORT:-6162}
      - BIN_LIMITS={form="16 MiB"}
    volumes:
      - ${CONTAINER_BASEPATH:-/opt/basedbin}:/upload
    #ports:
    #  - ${BIN_PORT:-6162}:${BIN_PORT:-6162}
    networks:
      proxy:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.rtr-basedbin.entrypoints=https
      - traefik.http.routers.rtr-basedbin.rule=Host(`${TRAEFIK_SUBJECT_CN:?}`)
      - traefik.http.services.svc-basedbin.loadbalancer.server.scheme=http
      - traefik.http.services.svc-basedbin.loadbalancer.server.port=${BIN_PORT:-6162}
      - traefik.http.routers.rtr-basedbin.service=svc-basedbin