networks:
  stack:
  proxy:
    external: true

services:
  yabin:
    ## https://github.com/Yureien/YABin
    image: yureien/yabin:latest
    container_name: ${CONTAINER_NAME:-yabin}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - stack
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.rtr-yabin.entrypoints=https
      - traefik.http.routers.rtr-yabin.rule=Host(`${TRAEFIK_SUBJECT_CN:?}`)
      - traefik.http.services.svc-yabin.loadbalancer.server.scheme=http
      - traefik.http.services.svc-yabin.loadbalancer.server.port=${PORT:-3000}
      - traefik.http.routers.rtr-yabin.service=svc-yabin

  db:
    image: postgres:15-alpine
    container_name: ${CONTAINER_DB_NAME:-yabin_db}
    hostname: ${HOSTNAME}
    restart: always
    environment:
      - TZ=${TZ:-UTC}
      - POSTGRES_USER=${DB_USER:-yabin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?}
      - POSTGRES_DB=${DB_NAME:-yabin}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ${CONTAINER_DB_BASEPATH:-${CONTAINER_BASEPATH:-/opt/yabin}/db}:/var/lib/postgresql/data
    networks:
      - stack