networks:
  proxy:
    external: true

services:
  librespeed:
    image: ghcr.io/librespeed/speedtest:latest
    container_name: ${CONTAINER_NAME:-librespeed}
    hostname: ${CONTAINER_HOSTNAME:-${HOSTNAME}}
    restart: unless-stopped
    environment:
      - MODE=standalone
      - WEBPORT=${WEBPORT:-80}
      - TITLE
      - TELEMETRY=${TELEMETRY:-false}
      - EMAIL=${EMAIL:-recipient@example.com}
      - ENABLE_ID_OBFUSCATION=${ENABLE_ID_OBFUSCATION:-false}
      - REDACT_IP_ADDRESSES=${REDACT_IP_ADDRESSES:-false}
      - IPINFO_APIKEY
      - DISABLE_IPINFO=${DISABLE_IPINFO:-false}
      - DISTANCE=km
      - PASSWORD=${PASSWORD:-Key4-Statistics-Page}
    volumes:
      - ${CONTAINER_BASEPATH}:/database
    #ports:
    #  - ${CONTAINER_PORT_HTTP:-${WEBPORT:-80}}:${WEBPORT:-80}
    networks:
      proxy:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.middlewares.${TRAEFIK_SERVICE:-librespeed}-bouncer.plugin.crowdsecBouncer.crowdseclapikey=${CROWDSEC_LAPIKEY:-}
      - traefik.http.middlewares.${TRAEFIK_SERVICE:-librespeed}-bouncer.plugin.crowdsecBouncer.crowdseclapischeme=${CROWDSEC_LAPISCHEME:-http}
      - traefik.http.middlewares.${TRAEFIK_SERVICE:-librespeed}-bouncer.plugin.crowdsecBouncer.crowdseclapihost=${CROWDSEC_LAPIHOSTNAME:-crowdsec}:${CROWDSEC_LAPIHOSTPORT:-8080}
      - traefik.http.routers.${TRAEFIK_SERVICE:-librespeed}.middlewares=${TRAEFIK_SERVICE:-librespeed}-bouncer
      - traefik.http.routers.${TRAEFIK_SERVICE:-librespeed}.entrypoints=https
      - traefik.http.routers.${TRAEFIK_SERVICE:-librespeed}.rule=${TRAEFIK_ROUTER_RULE:-Host(`${TRAEFIK_SUBJECT_CN:?TRAEFIK_ROUTER_RULE is missing}`)}
      - traefik.http.routers.${TRAEFIK_SERVICE:-librespeed}.tls=true
      - traefik.http.routers.${TRAEFIK_SERVICE:-librespeed}.tls.certresolver=${TRAEFIK_CERTRESOLVER:-le_cloudflare}
      - traefik.http.routers.${TRAEFIK_SERVICE:-librespeed}.tls.domains[0].main=${TRAEFIK_SUBJECT_CN:?TRAEFIK_SUBJECT_CN is missing}
      - traefik.http.routers.${TRAEFIK_SERVICE:-librespeed}.service=${TRAEFIK_SERVICE:-librespeed}
      - traefik.http.services.${TRAEFIK_SERVICE:-librespeed}.loadbalancer.server.scheme=${TRAEFIK_SERVICE_SCHEME:-http}
      - traefik.http.services.${TRAEFIK_SERVICE:-librespeed}.loadbalancer.server.port=${TRAEFIK_SERVICE_PORT:-${WEBPORT:-80}}
