networks:
  proxy:
    external: true

services:
  librespeed:
    image: ghcr.io/librespeed/speedtest:latest
    container_name: ${CONTAINER_NAME:-librespeed}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
      - MODE=standalone
      - WEBPORT=${WEBPORT:-80}
      - TITLE
      - TELEMETRY=${TELEMETRY:-false}
      - EMAIL=${EMAIL:-recipient@example.com}
      - ENABLE_ID_OBFUSCATION=${ENABLE_ID_OBFUSCATION:-false}
      - REDACT_IP_ADDRESSES=${REDACT_IP_ADDRESSES:-false}
      - IPINFO_APIKEY
      - DISABLE_IPINFO=${DISABLE_IPINFO:-false}
      - DISTANCE=km
      - PASSWORD=${PASSWORD:-Key4-Statistics-Page}
    volumes:
      - ${CONTAINER_BASEPATH}:/database
    #ports:
    #  - ${WEBPORT:-80}:${WEBPORT:-80}
    networks:
      proxy:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.rtr-librespeed.entrypoints=https
      - traefik.http.routers.rtr-librespeed.rule=Host(`${TRAEFIK_SUBJECT_CN:?}`)
      - traefik.http.services.svc-librespeed.loadbalancer.server.scheme=http
      - traefik.http.services.svc-librespeed.loadbalancer.server.port=${WEBPORT:-80}
      - traefik.http.routers.rtr-librespeed.service=svc-librespeed