networks:
  proxy:
    external: true

services:
  glances:
    image: nicolargo/glances:latest
    container_name: ${CONTAINER_HOSTNAME:-glances}
    hostname: HOSTNAME}
    pid: host
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
      - GLANCES_OPT=${GLANCES_OPT:-"--webserver --port ${GLANCES_PORT:-61208}"}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONTAINER_BASEPATH:-/opt/glances}:/glances
    #ports:
    #  - ${GLANCES_PORT:-61208}:${GLANCES_PORT:-61208}
    networks:
      proxy:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.rtr-glances.entrypoints=https
      - traefik.http.routers.rtr-glances.rule=Host(`${TRAEFIK_SUBJECT_CN:?}`)
      - traefik.http.services.svc-glances.loadbalancer.server.scheme=http
      - traefik.http.services.svc-glances.loadbalancer.server.port=${GLANCES_PORT:-61208}
      - traefik.http.routers.rtr-glances.service=svc-glances