networks:
  proxy:
    external: true

services:
  ## Dozzle - Real-time Docker Log Viewer - https://dozzle.dev/
  dozzle:
    image: amir20/dozzle:latest
    container_name: ${CONTAINER_NAME:-dozzle}
    hostname: ${HOSTNAME}
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=${TZ:-UTC}
      - DOZZLE_ADDR=:${DOZZLE_ADDR:-8080}
      - DOZZLE_BASE=${DOZZLE_BASE:-/}
      - DOZZLE_HOSTNAME=${DOZZLE_HOSTNAME}
      - DOZZLE_LEVEL=info
      - DOZZLE_AUTH_PROVIDER=${DOZZLE_AUTH_PROVIDER:-none} # none, simple, forward-proxy
      - DOZZLE_AUTH_HEADER_USER=${DOZZLE_AUTH_HEADER_USER:-Remote-User}
      - DOZZLE_AUTH_HEADER_EMAIL=${DOZZLE_AUTH_HEADER_EMAIL:-Remote-Email}
      - DOZZLE_AUTH_HEADER_NAME=${DOZZLE_AUTH_HEADER_NAME:-Remote-Name}
      - DOZZLE_ENABLE_ACTIONS=${DOZZLE_ENABLE_ACTIONS:-false}
      # https://github.com/amir20/dozzle/blob/987c0e6cc4640fa4fda276c1fede8eb127c93527/docs/guide/filters.md
      # https://docs.docker.com/reference/cli/docker/container/ls/#filter
      - DOZZLE_FILTER=${DOZZLE_FILTER:-status=running}
      - DOZZLE_NO_ANALYTICS=${DOZZLE_NO_ANALYTICS:-false}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONTAINER_BASEPATH:-/opt/dozzle}:/data
    #ports:
    #  - ${DOZZLE_ADDR:-8080}:${DOZZLE_ADDR:-8080}
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.rtr-dozzle.entryPoints=https
      - traefik.http.routers.rtr-dozzle.rule=Host(`${TRAEFIK_SUBJECT_CN:?}`)
      - traefik.http.services.svc-dozzle.loadBalancer.server.scheme=http
      - traefik.http.services.svc-dozzle.loadBalancer.server.port=${DOZZLE_ADDR:-8080}
      - traefik.http.routers.rtr-dozzle.service=svc-dozzle