networks:
  proxy:
    external: true

services:
  firefox:
    # https://docs.linuxserver.io/images/docker-firefox/
    image: lscr.io/linuxserver/firefox:latest
    container_name: ${CONTAINER_NAME:-firefox}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    shm_size: "1gb"
    environment:
      - TZ=${TZ:-UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ${CONTAINER_BASEPATH:-/opt/firefox}:/config
    #ports:
    #  - 3000:3000
    #  - 3001:3001
    networks:
      proxy:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.rtr-firefox.entryPoints=https
      - traefik.http.routers.rtr-firefox.rule=Host(`${TRAEFIK_SUBJECT_CN:?}`)
      - traefik.http.services.svc-firefox.loadBalancer.server.scheme=http
      - traefik.http.services.svc-firefox.loadBalancer.server.port=3000
      - traefik.http.routers.rtr-firefox.service=svc-firefox
