services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: ${CONTAINER_NAME:-portainer}
    hostname: ${CONTAINER_HOSTNAME:-${HOSTNAME}}
    restart: unless-stopped
    #command:
    #  - --sslcert=
    #  - --sslkey=
    environment:
      - TZ=${TZ:-Europe/Copenhagen}
    ports:
      - ${CONTAINER_PORT_HTTPS:-9443}:9443
      - ${CONTAINER_PORT_HTTP:-9000}:9000
      - ${CONTAINER_PORT_API:-8000}:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ${CONTAINER_BASE_PATH:-/opt/portainer}:/data
