networks:
  stack:

services:
  agent:
    image: portainer/agent:latest
    container_name: ${CONTAINER_AGENT_NAME:-portainer_agent}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    #ports:
    #  - 9001:9001
    networks:
    - stack
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer-ce
    container_name: ${CONTAINER_NAME:-portainer}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    command:
      - -H tcp://tasks.agent:9001
      - --tlsskipverify
    #  - --sslcert=
    #  - --sslkey=
    environment:
      - TZ=${TZ:-UTC}
    ports:
      - 9443:9443
      - 9000:9000
      - 8000:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ${CONTAINER_BASE_PATH:-/opt/portainer}:/data
    networks:
      - stack
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager