services:
  portainer_agent:
    image: portainer/agent:latest
    container_name: ${CONTAINER_AGENT_NAME:-portainer_agent}
    hostname: ${CONTAINER_AGENT_HOSTNAME:-${HOSTNAME}}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Europe/Copenhagen}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - ${CONTAINER_AGENT_PORT_HTTP:-9001}:9001
