# docker network create proxy
networks:
  proxy:
    external: true

services:
  portainer:
    networks:
      proxy:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.rtr-portainer.entrypoints=https
      - traefik.http.routers.rtr-portainer.rule=Host(`${TRAEFIK_SUBJECT_CN:?}`)
      - traefik.http.services.svc-portainer.loadbalancer.server.scheme=http
      - traefik.http.services.svc-portainer.loadbalancer.server.port=9000
      - traefik.http.routers.rtr-portainer.service=svc-portainer