networks:
  stack:

services:
  agent:
    image: portainer/agent:latest
    container_name: ${CONTAINER_AGENT_NAME:-portainer_agent}
    hostname: ${CONTAINER_AGENT_HOSTNAME:-${HOSTNAME}}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Europe/Copenhagen}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - ${CONTAINER_AGENT_PORT_HTTP:-9001}:9001
    networks:
    - stack
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer-ce
    container_name: ${CONTAINER_NAME:-portainer}
    hostname: ${CONTAINER_HOSTNAME:-${HOSTNAME}}
    restart: unless-stopped
    command:
      - -H tcp://tasks.agent:9001
      - --tlsskipverify
    #  - --sslcert=
    #  - --sslkey=
    environment:
      - TZ=${TZ:-Europe/Copenhagen}
    ports:
      - ${CONTAINER_PORT_HTTPS:-9443}:9443
      - ${CONTAINER_PORT_HTTP:-9000}:9000
      - ${CONTAINER_PORT_API:-8000}:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ${CONTAINER_BASE_PATH:-/opt/portainer}:/data
    networks:
      - stack
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

