networks:
  proxy:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: ${CONTAINER_NAME:-kuma}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
    #  - PUID=1000
    #  - PGID=1000
      - UPTIME_KUMA_PORT=${UPTIME_KUMA_PORT:-3001}
    #  - UPTIME_KUMA_SSL_KEY=/app/data/cert.key # Path to SSL key
    #  - UPTIME_KUMA_SSL_CERT=/app/data/cert.pem # Path to SSL certificate
    #  - UPTIME_KUMA_SSL_KEY_PASSPHRASE # SSL Key Passphrase
    #  - UPTIME_KUMA_CLOUDFLARED_TOKEN # Cloudflare Tunnel Token - https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy-with-Cloudflare-Tunnel
    #  - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=false # By default, Uptime Kuma is not allowed in iframe if the domain name is not the same as the parent.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ${CONTAINER_BASEPATH:-/opt/docker/uptime-kuma}:/app/data
    #ports:
    #  - ${UPTIME_KUMA_PORT=:-3001}:${UPTIME_KUMA_PORT=:-3001}
    networks:
      proxy:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.rtr-kuma.entrypoints=https
      - traefik.http.routers.rtr-kuma.rule=Host(`${TRAEFIK_SUBJECT_CN:?}`)
      - traefik.http.services.svc-kuma.loadbalancer.server.scheme=http
      - traefik.http.services.svc-kuma.loadbalancer.server.port=${UPTIME_KUMA_PORT=:-3001}
      - traefik.http.routers.rtr-kuma.service=svc-kuma