services:
  ## https://docs.linuxserver.io/images/docker-altus/
  altus:
    image: lscr.io/linuxserver/altus:latest
    container_name: ${CONTAINER_NAME:-altus}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
      - PUID=${CONTAINER_UID:-1000}
      - PGID=${CONTAINER_GID:-1000}
      - CUSTOM_PORT=${CUSTOM_PORT:-3000}
      - CUSTOM_HTTPS_PORT=${CUSTOM_HTTPS_PORT:-3000}
      - CUSTOM_USER=${CUSTOM_USER:-abc}
      - PASSWORD=${CUSTOM_PASS:-abc}
      - TITLE=${TITLE:-WhatsApp - KasmVNC}
      - SUBFOLDER=${RPROXY_PATH}
    volumes:
      - ${CONTAINER_BASEPATH:-~/altus}:/config
    ports:
      - ${CUSTOM_PORT:-3000}:${CUSTOM_PORT:-3000}
      - ${CUSTOM_HTTPS_PORT:-3001}:${CUSTOM_HTTPS_PORT:-3000}
    shm_size: "1gb"
