services:
  ## https://docs.linuxserver.io/images/docker-altus/
  altus:
    image: lscr.io/linuxserver/altus:latest
    container_name: ${CONTAINER_NAME:-altus}
    hostname: ${CONTAINER_HOSTNAME:-${HOSTNAME}}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Europe/Copenhagen}
      - PUID=${CONTAINER_UID:-1000}
      - PGID=${CONTAINER_GID:-1000}
      - CUSTOM_PORT=${CUSTOM_PORT:-3000}
      - CUSTOM_HTTPS_PORT=${CUSTOM_HTTPS_PORT:-3000}
      - CUSTOM_USER=${CUSTOM_USER:-abc}
      - PASSWORD=${CUSTOM_PASS:-abc}
      - TITLE=${TITLE:-WhatsApp - KasmVNC}
      - SUBFOLDER=${RPROXY_PATH}
    volumes:
      - ${CONTAINER_BASEPATH:-./altus}:/config
    ports:
      - ${CONTAINER_PORT_HTTP:-${CUSTOM_PORT:-3000}}:${CUSTOM_PORT:-3000}
      - ${CONTAINER_PORT_HTTPS:-${CUSTOM_HTTPS_PORT:-3001}}:${CUSTOM_HTTPS_PORT:-3000}
    shm_size: "1gb"
