certificatesResolvers:
  le_dns_cf:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: ${TRAEFIK_ACME_EMAIL:?TRAEFIK_ACME_EMAIL is missing}
      storage: ${TRAEFIK_ACME_FILE:-${TRAEFIK_ACME_PATH:-/etc/traefik}/acme.json}
      keyType: RSA4096
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53