http:
  routers:
    rtr-default:
      tls:
        domains:
          - main: ${TRAEFIK_DEFAULT_SUBJECT_CN:?}
            sans: ${TRAEFIK_DEFAULT_SUBJECT_AN:?}
        certResolver: default
        options: modern
  middlewares:
    mdw-hsts:
      headers:
        customResponseHeaders:
          Strict-Transport-Security: "max-age=63072000"