tls:
  stores:
    default:
      #defaultCertificate:
      #  certFile: ${TRAEFIK_ACME_PATH:-/etc/traefik/certs}/default.crt
      #  keyFile: ${TRAEFIK_ACME_PATH:-/etc/traefik/certs}/default.key
      defaultGeneratedCert:
        resolver: le_dns_cf
        domain:
          main: ${TRAEFIK_DEFAULT_SUBJECT_CN}
          sans: ${TRAEFIK_DEFAULT_SUBJECT_AN}
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_ARIA_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CAMELLIA_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECCPWD_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_PSK_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_AES_128_GCM_SHA256
        - TLS_ECCPWD_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_PSK_WITH_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
