# https://ssl-config.mozilla.org/
# https://ciphersuite.info/
tls:
  stores:
    default:
      #defaultCertificate:
      #  certFile: ${TRAEFIK_ACME_PATH:-/etc/traefik/certs}/default.crt
      #  keyFile: ${TRAEFIK_ACME_PATH:-/etc/traefik/certs}/default.key
      defaultGeneratedCert:
        resolver: default
        domain:
          main: ${TRAEFIK_DEFAULT_SUBJECT_CN:?}
          sans: ${TRAEFIK_DEFAULT_SUBJECT_AN:?}
  options:
    default:
      minVersion: VersionTLS13