networks:
  stack:
  proxy:
    external: true

services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: ${CONTAINER_NAME:-searxng}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
      #- SEARXNG_SETTINGS_PATH=${SEARXNG_SETTINGS_PATH:-/etc/searxng/settings.yaml}
      #- SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      #- INSTANCE_NAME=SearXNG
      #- AUTOCOMPLETE=
      #- BASE_URL=
      #- MORTY_KEY=
      #- MORTY_URL=
      #- BIND_ADDRESS=${BIND_ADDRESS:-0.0.0.0:8080}
    volumes:
      - ${CONTAINER_BASEPATH:-/opt/searxng}:/etc/searxng
    ports:
      - 8080:8080
    networks:
      proxy:
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.rtr-searxng.entryPoints=https
      - traefik.http.routers.rtr-searxng.rule=Host(`${TRAEFIK_SUBJECT_CN:?}`)
      - traefik.http.services.svc-searxng.loadbalancer.server.scheme=http
      - traefik.http.services.svc-searxng.loadbalancer.server.port=8080
      - traefik.http.routers.rtr-searxng.service=svc-searxng