networks:
  proxy:
    external: true

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: ${CONTAINER_NAME:-nginx-proxy-manager}
    hostname: ${CONTAINER_HOSTNAME:-${HOSTNAME}}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Europe/Copenhagen}
      - PUID=1000
      - PGID=1000
      - DB_SQLITE_FILE=/data/npm.sqlite
      #- INITIAL_ADMIN_EMAIL
      #- INITIAL_ADMIN_PASSWORD
      #- DISABLE_IPV6
      #- DEBUG
      #- LE_STAGING
      #- X_FRAME_OPTIONS
    volumes:
      - ${CONTAINER_BASEPATH:-/opt/nginx-proxy-manager}:/data
      - ${CONTAINER_BASEPATH:-/opt/nginx-proxy-manager}/letsencrypt:/etc/letsencrypt
    ports:
      - ${CONTAINER_PORT_HTTP:-80}:80
      - ${CONTAINER_PORT_HTTPS:-443}:443
      - ${CONTAINER_PORT_MGMT:-81}:81
    networks:
      - proxy
    healthcheck:
      test: /bin/check-health
      interval: 10s
      timeout: 3s
