services:
  metabase:
    image: metabase/metabase:latest
    container_name: ${CONTAINER_MB_NAME:-metabase}
    hostname: ${CONTAINER_MB_HOSTNAME:-${HOSTNAME}}
    restart: always
    depends_on:
      - crowdsec
    environment:
      - MB_DB_TYPE=h2
      - MB_DB_FILE=/metabase-data/metabase.db
      - MB_ANON_TRACKING_ENABLED=false
    volumes:
      - ${CONTAINER_MB_BASEPATH:-${CONTAINER_BASEPATH:-/opt/crowdsec}/metabase-data}:/metabase-data
    ports:
      - ${CONTAINER_MB_PORT_HTTP:-3000}:3000
    networks:
      - proxy
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
